### PR TITLE
WIP: Add new version CentOS X dropping old verions

### PR DESCRIPTION
**Pull request by junaruga**
This PR is still **working in progress**.
But I decided to share this PR as I need your advises.

The situation is ...

As current exist `7.2.1511-${arch}` 's image URLs do not exist except x86_64, those do not work.
I updated to latest CentOS 7.6 (or 7.5) image files.
Then, `x86_64` and `armhfp` work.
But other archs do not work. (`docker build -t $repo:$version-iso iso` works, but `docker run -it --rm $repo:$version-iso ...` does not work.)

Here is my repository's result.
https://travis-ci.org/junaruga/centos/builds/531571388

Could you give me some advises?

Thank you.

----
## Other notable features

* Install libguestfs-tools to use virt-tar-out command from xenial repo.
  We can not install it from bionic repo because of below error.

  The following packages have unmet dependencies:
  libguestfs-tools : Depends: libguestfs0 (= 1:1.36.13-1ubuntu3) but it is not going to be installed
                     Depends: libguestfs-perl (= 1:1.36.13-1ubuntu3) but it is not going to be installed
  E: Unable to correct problems, you have held broken packages.

* Update qemu v3.1.0-3.
* Rafactoring mixed indent with spaces and tab, replacing tab to spaces.

* A bug of `virt-tar-out` command to convert iso file to tar file?
  I am asking it to the upstream project here. https://github.com/libguestfs/libguestfs/issues/37

### CODE REVIEW

**Comment by rwmjones** [comment]
Please post patches on the mailing list where we can review them using open tools.

**Comment by lafin** [comment]
The PR accidentally merged. Please reopen PR.

**Comment by junaruga** [comment]
@lafin 

> The PR accidentally merged. Please reopen PR.

I can not reopen this PR. It's not like issue ticket page. It's a specification of GitHub.

You mean that new PR to include a commit that do `git revert` this PR's commit, right?

**Comment by junaruga** [comment]
@lafin Ah I understand what you mentioned.
You canceled this PR during this PR is being merged to the master branch. This PR is actually not merged to the master branch yet.
Sure, I open another PR.

**Pull request merged**
