### PR TITLE
Add new version CentOS 7.6 dropping old versions

### PR DESCRIPTION
**Pull request by junaruga**
It's same with another PR (https://github.com/multiarch/centos/pull/9) that was wrongly merged and canceled.

But I decided to share this PR, because I need your advises.

The situation is ...

As current exist `7.2.1511-${arch}` 's image URLs do not exist except x86_64, those do not work.
I updated to latest CentOS 7.6 (or 7.5) image files.
Then, `x86_64` and `armhfp` work.
But other archs do not work. (`docker build -t $repo:$version-iso iso` works, but `docker run -it --rm $repo:$version-iso ...` does not work.)

Here is my repository's result.
https://travis-ci.org/junaruga/centos/builds/531571388

Could you give me some advises?

Thank you.

----
## Other notable features

* Install libguestfs-tools to use virt-tar-out command from xenial repo.
  We can not install it from bionic repo because of below error.

  The following packages have unmet dependencies:
  libguestfs-tools : Depends: libguestfs0 (= 1:1.36.13-1ubuntu3) but it is not going to be installed
                     Depends: libguestfs-perl (= 1:1.36.13-1ubuntu3) but it is not going to be installed
  E: Unable to correct problems, you have held broken packages.

* Update qemu v3.1.0-3.
* Rafactoring mixed indent with spaces and tab, replacing tab to spaces.

* A bug of `virt-tar-out` command to convert iso file to tar file?
  After I asked it to the upstream project here. https://github.com/libguestfs/libguestfs/issues/37 , they recommended using `guestfish` instead of `virt-tar-out` for the issue case.

### CODE REVIEW

**Comment by junaruga** [comment]
@moul @moul-sudo I appreciate if you give me some advices for this PR when you have a time.

* armhfp container run (`docker run`) that is from "*.raw.xz" is succeeded.
* x86_64 containers run (`docker run`) that are from "*.qcow2" are succeeded.
* Other arch containers run (`docker run`) that are from "*.iso" are invalid. Failed to run `docker run` with the containers.

Detail: https://travis-ci.org/multiarch/centos/builds/531722254

**Comment by junaruga** [comment]
I rebased to pass the CI.
I tried some ways to solve the invalid container images' issue.
But as I could not solve it, I commented out those cases.
I think this PR is still better than current master branch and CI's situation.
Shall we merge this?

As a note, I removed Dockerfile files on the repository.
As those are generated in `update.sh`, I think we do not have to keep those on the repository.

**Comment by junaruga** [comment]
@lafin could you review this PR?

**Review by lafin — APPROVED** [review]

**Comment by junaruga** [comment]
@lafin thanks for your review. I merged it now.

**Pull request merged**
